// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ChapterDocumentDataSlicesSlice =
  | TextAndSymbolSlice
  | RichContentSlice
  | PrioritiesSlice
  | CanvasSlice
  | DownloadSlice
  | HeroSlice
  | SliderSlice;

/**
 * Content for Chapter documents
 */
interface ChapterDocumentData {
  /**
   * Slice Zone field in *Chapter*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: chapter.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ChapterDocumentDataSlicesSlice> /**
   * Meta Description field in *Chapter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: chapter.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Chapter*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: chapter.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Chapter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: chapter.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Chapter document from Prismic
 *
 * - **API ID**: `chapter`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChapterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ChapterDocumentData>,
    "chapter",
    Lang
  >;

/**
 * Item in *Footer → Links*
 */
export interface FooterDocumentDataLinksItem {
  /**
   * Link field in *Footer → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *Footer → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<FooterDocumentDataLinksItem>>;

  /**
   * LinkedIn field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.linkedin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;

  /**
   * Facebook field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.facebook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField;

  /**
   * X field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.twitter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter: prismic.LinkField;

  /**
   * Instagram field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Home → Gallery*
 */
export interface HomeDocumentDataGalleryItem {
  /**
   * Image field in *Home → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Home → Chapters*
 */
export interface HomeDocumentDataChaptersItem {
  /**
   * Title field in *Home → Chapters*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.chapters[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Home → Chapters*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.chapters[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Paragraph field in *Home → Chapters*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.chapters[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Link field in *Home → Chapters*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.chapters[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Symbol field in *Home → Chapters*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.chapters[].symbol
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  symbol: prismic.ImageField<never>;

  /**
   * Button Text field in *Home → Chapters*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.chapters[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Item in *Home → Statistics*
 */
export interface HomeDocumentDataStatisticsItem {
  /**
   * Number field in *Home → Statistics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.statistics[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;

  /**
   * Title field in *Home → Statistics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.statistics[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Header Title Line 1 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.header_title_line_one
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_title_line_one: prismic.KeyTextField;

  /**
   * Header Title Line 2 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.header_title_line_two
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_title_line_two: prismic.KeyTextField;

  /**
   * Header Title Line 3 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.header_title_line_three
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_title_line_three: prismic.KeyTextField;

  /**
   * Header Subtitle field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.header_subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_subtitle: prismic.KeyTextField;

  /**
   * Header Paragraph field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.header_paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_paragraph: prismic.KeyTextField;

  /**
   * Gallery Title Line 1 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.gallery_title_one
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  gallery_title_one: prismic.KeyTextField;

  /**
   * Gallery Title Line 2 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.gallery_title_two
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  gallery_title_two: prismic.KeyTextField;

  /**
   * Gallery Paragraph field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.gallery_paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  gallery_paragraph: prismic.KeyTextField;

  /**
   * Gallery field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<HomeDocumentDataGalleryItem>>;

  /**
   * Section One Title Line 1 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.section_one_title_line_one
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_one_title_line_one: prismic.KeyTextField;

  /**
   * Section One Title Line 2 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.section_one_title_line_two
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_one_title_line_two: prismic.KeyTextField;

  /**
   * Section One Title Line 3 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.section_one_title_line_three
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_one_title_line_three: prismic.KeyTextField;

  /**
   * Section One Text field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.section_one_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_one_text: prismic.RichTextField;

  /**
   * Section One Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.section_one_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  section_one_image: prismic.ImageField<never>;

  /**
   * Section Two Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.section_two_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_two_title: prismic.KeyTextField;

  /**
   * Section Two Text field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.section_two_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_two_text: prismic.RichTextField;

  /**
   * Section Two Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.section_two_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  section_two_image: prismic.ImageField<never>;

  /**
   * Chapters field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.chapters[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  chapters: prismic.GroupField<Simplify<HomeDocumentDataChaptersItem>>;

  /**
   * Statistics field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.statistics[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  statistics: prismic.GroupField<Simplify<HomeDocumentDataStatisticsItem>>;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Metadata documents
 */
interface MetadataDocumentData {
  /**
   * Favicon field in *Metadata*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.favicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  favicon: prismic.ImageField<never>;

  /**
   * Title field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Metadata*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Metadata*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Metadata document from Prismic
 *
 * - **API ID**: `metadata`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MetadataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MetadataDocumentData>,
    "metadata",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Text field in *Navigation → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;

  /**
   * Action Days title field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.action_days_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_days_title: prismic.KeyTextField;

  /**
   * Action Days link field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.action_days_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  action_days_link: prismic.LinkField;

  /**
   * Sof title field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.sof_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sof_title: prismic.KeyTextField;

  /**
   * Sof link field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.sof_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sof_link: prismic.LinkField;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

export type AllDocumentTypes =
  | ChapterDocument
  | FooterDocument
  | HomeDocument
  | MetadataDocument
  | NavigationDocument;

/**
 * Primary content in *Canvas → Default → Primary*
 */
export interface CanvasSliceDefaultPrimary {
  /**
   * Title Line 1 field in *Canvas → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: canvas.default.primary.title_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_one: prismic.KeyTextField;

  /**
   * Title Line 2 field in *Canvas → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: canvas.default.primary.title_second
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_second: prismic.KeyTextField;

  /**
   * Title Line 3 field in *Canvas → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: canvas.default.primary.title_third
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_third: prismic.KeyTextField;

  /**
   * Paragraph text field in *Canvas → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: canvas.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image Left field in *Canvas → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: canvas.default.primary.image_left
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_left: prismic.ImageField<never>;

  /**
   * Image Right field in *Canvas → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: canvas.default.primary.image_right
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_right: prismic.ImageField<never>;
}

/**
 * Default variation for Canvas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CanvasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CanvasSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Canvas*
 */
type CanvasSliceVariation = CanvasSliceDefault;

/**
 * Canvas Shared Slice
 *
 * - **API ID**: `canvas`
 * - **Description**: Canvas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CanvasSlice = prismic.SharedSlice<"canvas", CanvasSliceVariation>;

/**
 * Item in *Download → Default → Primary → Downloads*
 */
export interface DownloadSliceDefaultPrimaryDownloadsItem {
  /**
   * Image field in *Download → Default → Primary → Downloads*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: download.default.primary.downloads[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Title field in *Download → Default → Primary → Downloads*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: download.default.primary.downloads[].image_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_title: prismic.KeyTextField;

  /**
   * Image Subtitle field in *Download → Default → Primary → Downloads*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: download.default.primary.downloads[].image_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_subtitle: prismic.KeyTextField;

  /**
   * File field in *Download → Default → Primary → Downloads*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: download.default.primary.downloads[].file
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  file: prismic.LinkToMediaField;
}

/**
 * Primary content in *Download → Default → Primary*
 */
export interface DownloadSliceDefaultPrimary {
  /**
   * Title field in *Download → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: download.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Download → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: download.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Downloads field in *Download → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: download.default.primary.downloads[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  downloads: prismic.GroupField<
    Simplify<DownloadSliceDefaultPrimaryDownloadsItem>
  >;
}

/**
 * Default variation for Download Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DownloadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DownloadSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Download*
 */
type DownloadSliceVariation = DownloadSliceDefault;

/**
 * Download Shared Slice
 *
 * - **API ID**: `download`
 * - **Description**: Download
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DownloadSlice = prismic.SharedSlice<
  "download",
  DownloadSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * paragraph field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Priorities → Default → Primary → Priorities*
 */
export interface PrioritiesSliceDefaultPrimaryPrioritiesItem {
  /**
   * Title field in *Priorities → Default → Primary → Priorities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: priorities.default.primary.priorities[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Priorities → Default → Primary*
 */
export interface PrioritiesSliceDefaultPrimary {
  /**
   * Paragraph field in *Priorities → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: priorities.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Priorities field in *Priorities → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: priorities.default.primary.priorities[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  priorities: prismic.GroupField<
    Simplify<PrioritiesSliceDefaultPrimaryPrioritiesItem>
  >;
}

/**
 * Default variation for Priorities Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrioritiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrioritiesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Priorities*
 */
type PrioritiesSliceVariation = PrioritiesSliceDefault;

/**
 * Priorities Shared Slice
 *
 * - **API ID**: `priorities`
 * - **Description**: Priorities
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrioritiesSlice = prismic.SharedSlice<
  "priorities",
  PrioritiesSliceVariation
>;

/**
 * Primary content in *RichContent → Text Left Image Right → Primary*
 */
export interface RichContentSliceDefaultPrimary {
  /**
   * Title field in *RichContent → Text Left Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *RichContent → Text Left Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *RichContent → Text Left Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Background Symbol Direction Select field in *RichContent → Text Left Image Right → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.default.primary.bg_symbol_direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_symbol_direction: prismic.SelectField<
    "Arrows facing up" | "Arrows facing right"
  >;

  /**
   * Background Symbol Position field in *RichContent → Text Left Image Right → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: rich_content.default.primary.bg_symbol_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_symbol_position: prismic.SelectField<"center" | "right", "filled">;
}

/**
 * Text Left Image Right variation for RichContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *RichContent → Text Right Image Left → Primary*
 */
export interface RichContentSliceTextRightImageLeftPrimary {
  /**
   * Title field in *RichContent → Text Right Image Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.textRightImageLeft.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *RichContent → Text Right Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.textRightImageLeft.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *RichContent → Text Right Image Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.textRightImageLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Background Symbol Direction field in *RichContent → Text Right Image Left → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.textRightImageLeft.primary.bg_symbol_direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_symbol_direction: prismic.SelectField<
    "Arrows facing up" | "Arrows facing right"
  >;

  /**
   * Background Symbol Position field in *RichContent → Text Right Image Left → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: rich_content.textRightImageLeft.primary.bg_symbol_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_symbol_position: prismic.SelectField<"center" | "right", "filled">;
}

/**
 * Text Right Image Left variation for RichContent Slice
 *
 * - **API ID**: `textRightImageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichContentSliceTextRightImageLeft = prismic.SharedSliceVariation<
  "textRightImageLeft",
  Simplify<RichContentSliceTextRightImageLeftPrimary>,
  never
>;

/**
 * Primary content in *RichContent → Text Top Image Bottom → Primary*
 */
export interface RichContentSliceTextTopImageBottomPrimary {
  /**
   * Title field in *RichContent → Text Top Image Bottom → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.textTopImageBottom.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *RichContent → Text Top Image Bottom → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.textTopImageBottom.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *RichContent → Text Top Image Bottom → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.textTopImageBottom.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Background Symbol Direction field in *RichContent → Text Top Image Bottom → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_content.textTopImageBottom.primary.bg_symbol_direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_symbol_direction: prismic.SelectField<
    "Arrows facing up" | "Arrows facing right"
  >;

  /**
   * Background Symbol Position field in *RichContent → Text Top Image Bottom → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: rich_content.textTopImageBottom.primary.bg_symbol_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_symbol_position: prismic.SelectField<"center" | "right", "filled">;
}

/**
 * Text Top Image Bottom variation for RichContent Slice
 *
 * - **API ID**: `textTopImageBottom`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichContentSliceTextTopImageBottom = prismic.SharedSliceVariation<
  "textTopImageBottom",
  Simplify<RichContentSliceTextTopImageBottomPrimary>,
  never
>;

/**
 * Slice variation for *RichContent*
 */
type RichContentSliceVariation =
  | RichContentSliceDefault
  | RichContentSliceTextRightImageLeft
  | RichContentSliceTextTopImageBottom;

/**
 * RichContent Shared Slice
 *
 * - **API ID**: `rich_content`
 * - **Description**: RichContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichContentSlice = prismic.SharedSlice<
  "rich_content",
  RichContentSliceVariation
>;

/**
 * Item in *Slider → Default → Primary → Slides*
 */
export interface SliderSliceDefaultPrimarySlidesItem {
  /**
   * Title field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Slider → Default → Primary → Slides*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Primary content in *Slider → Default → Primary*
 */
export interface SliderSliceDefaultPrimary {
  /**
   * Slides field in *Slider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slides[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slides: prismic.GroupField<Simplify<SliderSliceDefaultPrimarySlidesItem>>;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

/**
 * Primary content in *TextAndSymbol → Default → Primary*
 */
export interface TextAndSymbolSliceDefaultPrimary {
  /**
   * Title Line 1 field in *TextAndSymbol → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_symbol.default.primary.title_line_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_line_one: prismic.KeyTextField;

  /**
   * Title Line 2 field in *TextAndSymbol → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_symbol.default.primary.title_line_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_line_two: prismic.KeyTextField;

  /**
   * Title Line 3 field in *TextAndSymbol → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_symbol.default.primary.title_line_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_line_three: prismic.KeyTextField;

  /**
   * Text field in *TextAndSymbol → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_symbol.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TextAndSymbol Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndSymbolSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextAndSymbolSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextAndSymbol*
 */
type TextAndSymbolSliceVariation = TextAndSymbolSliceDefault;

/**
 * TextAndSymbol Shared Slice
 *
 * - **API ID**: `text_and_symbol`
 * - **Description**: TextAndSymbol
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndSymbolSlice = prismic.SharedSlice<
  "text_and_symbol",
  TextAndSymbolSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ChapterDocument,
      ChapterDocumentData,
      ChapterDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLinksItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataGalleryItem,
      HomeDocumentDataChaptersItem,
      HomeDocumentDataStatisticsItem,
      HomeDocumentDataSlicesSlice,
      MetadataDocument,
      MetadataDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      AllDocumentTypes,
      CanvasSlice,
      CanvasSliceDefaultPrimary,
      CanvasSliceVariation,
      CanvasSliceDefault,
      DownloadSlice,
      DownloadSliceDefaultPrimaryDownloadsItem,
      DownloadSliceDefaultPrimary,
      DownloadSliceVariation,
      DownloadSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PrioritiesSlice,
      PrioritiesSliceDefaultPrimaryPrioritiesItem,
      PrioritiesSliceDefaultPrimary,
      PrioritiesSliceVariation,
      PrioritiesSliceDefault,
      RichContentSlice,
      RichContentSliceDefaultPrimary,
      RichContentSliceTextRightImageLeftPrimary,
      RichContentSliceTextTopImageBottomPrimary,
      RichContentSliceVariation,
      RichContentSliceDefault,
      RichContentSliceTextRightImageLeft,
      RichContentSliceTextTopImageBottom,
      SliderSlice,
      SliderSliceDefaultPrimarySlidesItem,
      SliderSliceDefaultPrimary,
      SliderSliceVariation,
      SliderSliceDefault,
      TextAndSymbolSlice,
      TextAndSymbolSliceDefaultPrimary,
      TextAndSymbolSliceVariation,
      TextAndSymbolSliceDefault,
    };
  }
}
