// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  canvas: defineAsyncComponent(() => import("./Canvas/index.vue")),
  download: defineAsyncComponent(() => import("./Download/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  priorities: defineAsyncComponent(() => import("./Priorities/index.vue")),
  rich_content: defineAsyncComponent(() => import("./RichContent/index.vue")),
  slider: defineAsyncComponent(() => import("./Slider/index.vue")),
  text_and_symbol: defineAsyncComponent(
    () => import("./TextAndSymbol/index.vue"),
  ),
});
